### ISSUE TITLE
Consider Adding a License

### ISSUE THREAD

**Issue by newnix** [phil-huxford/UNIX-Password-Manager#1]
Hi, found this from your post on Reddit.

Since this is publicly available code, consider adding a License if you haven't yet. Without a license, at least under US copyright, this defaults to "All Rights Reserved", making it a proprietary codebase with publicly visible code, sometimes called "source available".

If you want to effectively commit it to the public domain, consider using the 0BSD license, if you'd rather strong Copyleft, some version of the GPL might be appropriate, and for a more permissive license, the MIT, ISC, and 2BSD licenses are all great choices with very minor differences. You might also want to visit [this site](https://choosealicense.com/) to help in deciding which license, if any is best suited for this code.

**Comment by phil-huxford** [comment]
GNU GPLv3 license added.
