### ISSUE TITLE
Improve Shebang

### ISSUE THREAD

**Issue by newnix** [phil-huxford/UNIX-Password-Manager#2]
The current shebang is `#!/usr/bin/ksh93`, which is great for systems with exactly that path, though if you want to ensure it can find `ksh93` even if it may not be in that exact location, use `#!/usr/bin/env ksh93`. This form is recommended for all shells other than the POSIX defined `#!/bin/sh`, as it reduces the likelihood of running into issues such as `ksh93` actually being located at `/bin/ksh93` or `/usr/local/bin/ksh93` from causing your script to fail.

Additionally, while you specified this is for AIX, and I'm not familiar with AIX, it'd be worth checking whether or not you can just use `#!/usr/bin/env ksh` without specifying the version of Korn Shell being used (in this case AT&T's Korn shell).

**Comment by phil-huxford** [comment]
Shebang updated to `#!/usr/bin/env ksh93`.

`ksh88` limits the size of arrays to 4,095. Some older Korn Shell releases like the one on HP-UX limit the size to 1,023. This size limitation may not be acceptable depending on the scale of your production environment. 

(`ksh93` has a size limit of 419,4303)
